---
- hosts: '{{ host }}'
  connection: local
 
  
  tasks:
    - name: Configure NetFlow
      ios_config:
        lines:
          - flow Record NTARecord
          - match ipv4 source address
          - match ipv4 destination address
          - match ipv4 protocol
          - match transport destination-port
          - match interface input
          - collect interface output
          - collect counter bytes
          - collect counter packets
          - collect timestamp sys-uptime first
          - collect timestamp sys-uptime last
          - collect routing source as 
          - collect routing destination as 
          - flow exporter NTAExporter
          - destination 192.168.1.8
          - source g0
          - transport udp 2055
          - export-protocol netflow-v9
          - template data timeout 60
          - flow monitor NTAMonitor
          - record NTARecord
          - exporter NTAExporter
          - cache timeout active 60
          - cache timeout inactive 15
          - int gi0/0/0
          - ip flow monitor NTAMonitor output
